# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# RTD API version
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: >-
      3.11
  commands:
  - mkdir -pv "${READTHEDOCS_OUTPUT}"/html/
  - cp -rv docs/* "${READTHEDOCS_OUTPUT}"/html/
