# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# RTD API version
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: >-
      3.11
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/* $READTHEDOCS_OUTPUT/html/
    #- python -m venv "${READTHEDOCS_VIRTUALENV_PATH}"
    #- >-
      #"${READTHEDOCS_VIRTUALENV_PATH}"/bin/python -m pip install --exists-action=w -r requirements.in -c requirements.txt
    #- >-
      #"${READTHEDOCS_VIRTUALENV_PATH}"/bin/python deploy-html.py --output="$READTHEDOCS_OUTPUT/html/"
